version: '3.8'

services:
  tetris-game:
    build: .
    ports:
      - "8080:80"
    container_name: tetris-2d5
    restart: unless-stopped
    volumes:
      # Optional: Mount source code for development
      # - .:/usr/share/nginx/html
      # Optional: Custom nginx config
      # - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80 